[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

# Specific proxy for auth endpoints (more explicit)
[[redirects]]
  from = "/api/auth/*"
  to = "https://flowtrack-backend-87cf.onrender.com/api/auth/:splat"
  status = 200
  force = true

# General API proxy
[[redirects]]
  from = "/api/*"
  to = "https://flowtrack-backend-87cf.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200