[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

# More explicit proxy rules for debugging
[[redirects]]
  from = "/api/test/*"
  to = "https://flowtrack-backend-87cf.onrender.com/api/test/:splat"
  status = 200

[[redirects]]
  from = "/api/auth/*"
  to = "https://flowtrack-backend-87cf.onrender.com/api/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://flowtrack-backend-87cf.onrender.com/api/:splat"
  status = 200

# SPA fallback (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200