[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

# API proxy (must come before SPA fallback)
[[redirects]]
  from = "/api/*"
  to = "https://flowtrack-backend-87cf.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback for all non-API routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200